"""Initial migration

Revision ID: 29b5d17876b8
Revises: 
Create Date: 2025-02-28 22:34:36.591522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29b5d17876b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gem', 'type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('gem', 'gem_specification_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gemspecification', 'clarity',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('gemspecification', 'color',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gemspecification', 'color',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('gemspecification', 'clarity',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('gem', 'gem_specification_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gem', 'type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
